In [42]:
print("Welcome to Retail Sales Analytics Project!")

Welcome to Retail Sales Analytics Project!

In [43]:
import numpy as np
import pandas as pd

In [44]:
df=pd.read_csv("../Data/train.csv")

In [45]:
print("Data Profiling Starts")

Data Profiling Starts

In [46]:
print(df.head())
print(df.info())
print(df.describe())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.isnull().sum())
print(df.dtypes)

   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
1       2  CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520
2       3  CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045
3       4  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335
4       5  US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335

     Customer Name    Segment        Country             City       State  \
0      Claire Gute   Consumer  United States        Henderson    Kentucky
1      Claire Gute   Consumer  United States        Henderson    Kentucky
2  Darrin Van Huff  Corporate  United States      Los Angeles  California
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale     Florida

   Postal Code Region       Product ID         Category Sub-Category  \
0      42420.0  South  FUR-BO-10001798        Furniture    Bookcases
1      42420.0  South  FUR-CH-10000454        Furniture       Chairs
2      90036.0   West  OFF-LA-10000240  Office Supplies       Labels
3      33311.0  South  FUR-TA-10000577        Furniture       Tables
4      33311.0  South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales
0                  Bush Somerset Collection Bookcase  261.9600
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400
2  Self-Adhesive Address Labels for Typewriters b...   14.6200
3      Bretford CR4500 Series Slim Rectangular Table  957.5775
4                     Eldon Fold 'N Roll Cart System   22.3680
<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB
None
            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000
      Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class

     Customer ID     Customer Name    Segment        Country     City  \
9795    SH-19975     Sally Hughsby  Corporate  United States  Chicago
9796    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9797    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9798    CS-12490  Cindy Schnelling  Corporate  United States   Toledo
9799    CS-12490  Cindy Schnelling  Corporate  United States   Toledo

         State  Postal Code   Region       Product ID         Category  \
9795  Illinois      60610.0  Central  OFF-BI-10003429  Office Supplies
9796      Ohio      43615.0     East  OFF-AR-10001374  Office Supplies
9797      Ohio      43615.0     East  TEC-PH-10004977       Technology
9798      Ohio      43615.0     East  TEC-PH-10000912       Technology
9799      Ohio      43615.0     East  TEC-AC-10000487       Technology

     Sub-Category                                       Product Name    Sales
9795      Binders  Cardinal HOLDit! Binder Insert Strips,Extra St...    3.798
9796          Art           BIC Brite Liner Highlighters, Chisel Tip   10.368
9797       Phones                                        GE 30524EE4  235.188
9798       Phones           Anker 24W Portable Micro USB Car Charger   26.376
9799  Accessories                SanDisk Cruzer 4 GB USB Flash Drive   10.384
(9800, 18)
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='str')
Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64
Row ID             int64
Order ID             str
Order Date           str
Ship Date            str
Ship Mode            str
Customer ID          str
Customer Name        str
Segment              str
Country              str
City                 str
State                str
Postal Code      float64
Region               str
Product ID           str
Category             str
Sub-Category         str
Product Name         str
Sales            float64
dtype: object

In [47]:
print(df.nunique())

Row ID           9800
Order ID         4922
Order Date       1230
Ship Date        1326
Ship Mode           4
Customer ID       793
Customer Name     793
Segment             3
Country             1
City              529
State              49
Postal Code       626
Region              4
Product ID       1861
Category            3
Sub-Category       17
Product Name     1849
Sales            5757
dtype: int64

In [48]:
print(df['Region'].value_counts())
print(df['Category'].value_counts())
print(df['Sub-Category'].value_counts())

Region
West       3140
East       2785
Central    2277
South      1598
Name: count, dtype: int64
Category
Office Supplies    5909
Furniture          2078
Technology         1813
Name: count, dtype: int64
Sub-Category
Binders        1492
Paper          1338
Furnishings     931
Phones          876
Storage         832
Art             785
Accessories     756
Chairs          607
Appliances      459
Labels          357
Tables          314
Envelopes       248
Bookcases       226
Fasteners       214
Supplies        184
Machines        115
Copiers          66
Name: count, dtype: int64

In [49]:
df.to_csv("../Data/sales_cleaned.csv", index=False)

In [50]:
print("Data Profiling Completed")

Data Profiling Completed

In [51]:
print("Data Cleaning Starts")

Data Cleaning Starts

In [52]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [53]:
print(df['Order Date'].isnull().sum()/len(df)*100)

0.0

In [54]:
print(df['Postal Code'].isnull().sum()/len(df)*100)

0.11224489795918367

In [55]:
df["Row ID"].duplicated(keep=False).sum()

np.int64(0)

In [56]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='str')

In [57]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB
None

In [58]:
df.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [59]:
df.min()

Row ID                                                           1
Order ID                                            CA-2015-100006
Order Date                                              01/01/2018
Ship Date                                               01/01/2016
Ship Mode                                              First Class
Customer ID                                               AA-10315
Customer Name                                        Aaron Bergman
Segment                                                   Consumer
Country                                              United States
City                                                      Aberdeen
State                                                      Alabama
Postal Code                                                 1040.0
Region                                                     Central
Product ID                                         FUR-BO-10000112
Category                                                 Furniture
Sub-Category                                           Accessories
Product Name     "While you Were Out" Message Book, One Form pe...
Sales                                                        0.444
dtype: object

In [60]:
df.max()

Row ID                                         9800
Order ID                             US-2018-169551
Order Date                               31/12/2017
Ship Date                                31/12/2018
Ship Mode                            Standard Class
Customer ID                                ZD-21925
Customer Name                    Zuschuss Donatelli
Segment                                 Home Office
Country                               United States
City                                           Yuma
State                                       Wyoming
Postal Code                                 99301.0
Region                                         West
Product ID                          TEC-PH-10004977
Category                                 Technology
Sub-Category                                 Tables
Product Name     netTALK DUO VoIP Telephone Service
Sales                                      22638.48
dtype: object

In [61]:
print("Data Validation Starts")

Data Validation Starts

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [63]:
df["Ship Date"].head()

0    11/11/2017
1    11/11/2017
2    16/06/2017
3    18/10/2016
4    18/10/2016
Name: Ship Date, dtype: str

In [64]:
df["Customer ID"].head()

0    CG-12520
1    CG-12520
2    DV-13045
3    SO-20335
4    SO-20335
Name: Customer ID, dtype: str

In [65]:
df["Product ID"].head()

0    FUR-BO-10001798
1    FUR-CH-10000454
2    OFF-LA-10000240
3    FUR-TA-10000577
4    OFF-ST-10000760
Name: Product ID, dtype: str

In [66]:
df.duplicated().sum()

np.int64(0)

In [67]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [68]:
df["Ship Date"]=pd.to_datetime(df["Ship Date"],errors='coerce')

In [69]:
df["Ship Date"].isnull().sum()

np.int64(5985)

In [70]:
df["Ship Date"].isnull().sum()/len(df)*100

np.float64(61.07142857142858)

In [71]:
raw_df=pd.read_csv("../Data/train.csv")

In [72]:
raw_df[["Ship Date","Order Date"]].head()

    Ship Date  Order Date
0  11/11/2017  08/11/2017
1  11/11/2017  08/11/2017
2  16/06/2017  12/06/2017
3  18/10/2016  11/10/2016
4  18/10/2016  11/10/2016

In [73]:
raw_df[["Ship Date","Order Date"]].head(20)

     Ship Date  Order Date
0   11/11/2017  08/11/2017
1   11/11/2017  08/11/2017
2   16/06/2017  12/06/2017
3   18/10/2016  11/10/2016
4   18/10/2016  11/10/2016
5   14/06/2015  09/06/2015
6   14/06/2015  09/06/2015
7   14/06/2015  09/06/2015
8   14/06/2015  09/06/2015
9   14/06/2015  09/06/2015
10  14/06/2015  09/06/2015
11  14/06/2015  09/06/2015
12  20/04/2018  15/04/2018
13  10/12/2017  05/12/2017
14  26/11/2016  22/11/2016
15  26/11/2016  22/11/2016
16  18/11/2015  11/11/2015
17  15/05/2015  13/05/2015
18  01/09/2015  27/08/2015
19  01/09/2015  27/08/2015

In [75]:
raw_df[["Ship Date","Order Date"]].sample(20)

       Ship Date  Order Date
8801  12/11/2017  10/11/2017
1059  01/12/2017  24/11/2017
3580  29/07/2017  25/07/2017
8377  18/11/2016  12/11/2016
7798  27/03/2018  24/03/2018
1976  20/10/2015  18/10/2015
8380  14/09/2015  09/09/2015
8809  31/10/2018  26/10/2018
87    02/11/2018  26/10/2018
1567  30/11/2016  29/11/2016
2693  28/01/2017  22/01/2017
9153  29/09/2016  24/09/2016
8869  06/12/2018  01/12/2018
4339  01/09/2018  27/08/2018
8196  09/09/2018  05/09/2018
823   27/06/2018  20/06/2018
9739  21/03/2018  16/03/2018
6412  23/08/2018  17/08/2018
3075  24/07/2015  20/07/2015
3819  14/10/2018  09/10/2018

In [76]:
raw_df[["Ship Date","Order Date"]].dtypes

Ship Date     str
Order Date    str
dtype: object

In [77]:
raw_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [79]:
raw_df["Postal Code"].isnull().sum()

np.int64(11)